name: CI

on:
  push:
    branches:
      - main
  pull_request: ~
  workflow_dispatch: ~

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull images
        run: docker compose pull --ignore-pull-failures || true
      - name: Start services
        run: docker compose up --build -d
      - name: Wait for services
        run: |
          while status="$(docker inspect --format="{{if .Config.Healthcheck}}{{print .State.Health.Status}}{{end}}" "$(docker compose ps -q php)")"; do
            case $status in
              starting) sleep 1;;
              healthy) exit 0;;
              unhealthy)
                docker compose ps
                docker compose logs
                exit 1
              ;;
            esac
          done
          exit 1
      - name: Create JWT keys
        run: |
          docker compose exec php sh -c '
            set -e
            apk add openssl
            php bin/console lexik:jwt:generate-keypair
            setfacl -R -m u:www-data:rX -m u:"$(whoami)":rwX config/jwt
            setfacl -dR -m u:www-data:rX -m u:"$(whoami)":rwX config/jwt
          '
      - name: Create test database
        run: |
          docker compose exec php php bin/console doctrine:database:create --if-not-exists --env=test
          docker compose exec -T php php bin/console -e test doctrine:migrations:migrate --no-interaction
      - name: Seed test database
        run: docker compose exec -T php php bin/console doctrine:fixtures:load --no-interaction --env=test
      - name: PHPUnit
        run: docker compose exec -T php php bin/phpunit
      - name: Doctrine Schema Validator
        run: docker compose exec -T php php bin/console doctrine:schema:validate --skip-sync
