api_platform:
    title: Hello API Platform
    version: 1.0.0
    mapping:
        paths: [ '%kernel.project_dir%/src/Entity' ]
    patch_formats:
        json: [ 'application/merge-patch+json' ]
    # Mercure integration, remove if unwanted
    mercure: ~
    # Good cache defaults for REST APIs
    defaults:
        stateless: true
        normalization_context:
            skip_null_values: false
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    swagger:
        versions: [3]
        api_keys:
            JWT:
                name: Authorization
                type: header
