import ComplexNavbar from '@/components/navbar'
import './globals.css'
import AuthProvider from '@/providers/auth'
import { getServerSession } from 'next-auth'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children
}: {
  children: React.ReactNode
}) {

  const session = getServerSession()

  return (
    <html lang="fr">
      <AuthProvider>
        <body className="bg-slate-200 h-screen">
          {await session && (

            <div className='py-5'>
              <ComplexNavbar />
            </div>
          )}
          <div className=''>
            {children}
          </div>
        </body>
      </AuthProvider>
    </html>
  )
}
